
from pyhpeimc.auth import *
from pyhpeimc.plat.alarms import *

auth = IMCAuth("http://", "10.132.0.15", "8080", "admin", "admin")

alarms = get_realtime_alarm('admin', auth.creds, auth.url)
'''
print alarms[0]['faultDesc']
print type(alarms)
print len(alarms)
'''
data = {}
for alarm in alarms:
    print '----------------------------------------------------------------'
    '''
    print alarm['faultDesc']
    print alarm['id']
    print alarm['deviceDisplay']
    print alarm['severity']
    '''
    short_description = "Generated by HPE Intelligent Manage Center Alarm ID %s" % alarm['id']
    description = alarm['faultDesc']
    ip_address = alarm['deviceDisplay']
    identity = alarm['id']
    severity = alarm['severity']
    full_description = description+' Host IP address '+ip_address

    data['number'] = "IMC00"+str(identity)
    data['link'] = "https://dev30543.service-now.com/api/now/table/sys_user/6816f79cc0a8016401c5a33be04be441"
    data['impact'] = "2"
    data['priority'] = severity
    data['short_description']= short_description
    data['description'] = full_description


    print data
